In [1]:
##

In [ ]:
##Python Notes

if,elif, else Statements

In [39]:
if 3<4:
    print("NO WAYY!!")

NO WAYY!!


In [40]:
if 1==2:
    print('First')
else:
    print('Last')

Last


In [41]:
if 1 == 2:
    print('first')
elif 4 == 4:
    print('second')
elif 3 == 3:
    print('middle')
else:
    print('Last')

second


In [42]:
##only executes the first true condition and that is it

for Loops

In [44]:
seq = [1,2,3,4,5]
for item in seq:
    print(item)

1
2
3
4
5


In [46]:
for i in seq:
    print(i*i)

1
4
9
16
25


while Loops

In [47]:
i = 1

while i < 5:
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


In [48]:
for x in range(0,5):
    print (x)

0
1
2
3
4


In [49]:
for i in range(5):
    print(i)

0
1
2
3
4


list comprehension

In [51]:
x = [1,2,3,4]

In [52]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [53]:
[item**2 for item in x]

[1, 4, 9, 16]

functions

In [ ]:
def my_func(param1='default'):
    """
    Docstring goes here.
    """
    print(param1)

In [54]:
def square(x):
    return x**2

In [55]:
def func_mk(x,y,z):
    return 1+(2*x)*(4.5*y)/(.2*z)

lambda expressions¶

In [56]:
lambda var: var*2

<function __main__.<lambda>(var)>

In [57]:
t= lambda i:i**2

methods

In [58]:
st = 'hello my name is Sam'

In [59]:
st.lower()

'hello my name is sam'

In [60]:
st.upper()

'HELLO MY NAME IS SAM'

In [62]:
tweet = 'Go Sports! #Sports'

In [63]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [64]:
tweet.split('#')[1]

'Sports'

In [65]:
'x' in ['x','y','z']

True

In [ ]:
##Numpy##

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(2)

array([0.73481906, 0.54196177])

In [18]:
np.random.randn(2 # random normal 

array([-1.70608593, -1.15911942])

In [19]:
np.random.randint(1,100)

16

In [20]:
np.random.randint(1,100,10)

array([45,  1, 13, 18, 76, 80, 98, 94, 25, 37])

In [21]:
arr = np.arange(25)

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr = np.random.randint(0,50,10)

In [26]:
ranarr.max()


47

In [27]:
ranarr.argmax()


2

In [28]:
ranarr.min()


2

In [29]:
ranarr.argmin()

7

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
#NumPy Operations

In [34]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [35]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [36]:
np.max(arr) #same as arr.max()

24

In [37]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [38]:
np.log(arr)

/Users/mk/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [ ]:
##DataFrames##

In [2]:
import pandas as pd
import numpy as np

In [4]:
from numpy.random import randn
np.random.seed(101)

In [5]:
df = pd.DataFrame(randn(5,4),index=['A','B','C','D','E'],columns=['W','X','Y','Z'])

In [6]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
df['new'] = df['W'] + df['Y']

In [8]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

** Removing Columns**

In [9]:
df.drop('new',axis=1) ## AXIS =0 REFERS TO ROWS. AXIS =1 REFERS TO THE COLUMNS 

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [66]:
df.loc['A'] 

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
new    3.614819
Name: A, dtype: float64

In [70]:
df.iloc[0:2] 

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959

In [71]:
df.loc['B','Y']

-0.8480769834036315

In [72]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

Conditional Selection
An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [73]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [74]:
df>0

W      X      Y      Z    new
A   True   True   True   True   True
B   True  False  False   True  False
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [75]:
df[df>0]

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118       NaN       NaN  0.605965       NaN
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [76]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [77]:
df[(df['W']>0) & (df['Y'] > 1)] ## AND

W         X         Y         Z       new
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [78]:
df[(df['W']>0) | (df['Y'] > 1)] ## OR 

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [79]:
# Reset to default 0,1...n index
df.reset_index()

index         W         X         Y         Z       new
0     A  2.706850  0.628133  0.907969  0.503826  3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001 -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
4     E  0.190794  1.978757  2.605967  0.683509  2.796762

In [80]:
newind = 'CA NY WY OR CO'.split() # common method for splitting of blank list - easyw way to create a list 


In [81]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [82]:
df['States'] = newind

In [83]:
df

W         X         Y         Z       new States
A  2.706850  0.628133  0.907969  0.503826  3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509  2.796762     CO

In [84]:
df.set_index('States')

W         X         Y         Z       new
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.614819
NY      0.651118 -0.319318 -0.848077  0.605965 -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001 -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057 -0.744542
CO      0.190794  1.978757  2.605967  0.683509  2.796762

Multi-Index and Index Hierarchy
Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [85]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [86]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -0.229937 -1.283599
   2 -2.711192 -1.522410
   3 -1.416207  1.108544
G2 1  1.131029  0.498600
   2  1.179022  1.322684
   3  1.852155 -0.892172

In [87]:
df.index.names

FrozenList([None, None])

In [91]:
df

A         B
Group Num                    
G1    1   -0.229937 -1.283599
      2   -2.711192 -1.522410
      3   -1.416207  1.108544
G2    1    1.131029  0.498600
      2    1.179022  1.322684
      3    1.852155 -0.892172

In [92]:
df.index.names = ['Group','Num']

In [93]:
df

A         B
Group Num                    
G1    1   -0.229937 -1.283599
      2   -2.711192 -1.522410
      3   -1.416207  1.108544
G2    1    1.131029  0.498600
      2    1.179022  1.322684
      3    1.852155 -0.892172

In [89]:
df.loc['G2'].loc[2]['B']

1.3226843661409005

In [90]:
df.xs(['G1'])

A         B
Num                    
1   -0.229937 -1.283599
2   -2.711192 -1.522410
3   -1.416207  1.108544

In [94]:
df.xs(['G1',1])

A   -0.229937
B   -1.283599
Name: (G1, 1), dtype: float64

In [95]:
df.xs(1,level='Num')

A         B
Group                    
G1    -0.229937 -1.283599
G2     1.131029  0.498600

In [ ]:
f = plt.figure()
df3.ix[0:30].plot.area(alpha=0.4,ax=f.gca())
plt.legend(loc=' left', bbox_to_anchor=(1.0, 0.5))
plt.show()