In [1]:
import numpy as np

# NUMPY ARRAYS 

In [2]:
my_list= [1,2,3]

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
x=np.random.rand(5,5)

In [33]:
y=np.random.randn(4,4)

In [34]:
y

array([[ 0.16229374,  0.59701015, -0.15685354, -0.16420746],
       [ 3.74248306,  1.21190526,  0.96344592,  1.20361516],
       [-0.9347862 , -0.57845638, -0.34550261,  0.91827542],
       [ 1.08792556, -0.86361024, -0.02608963,  2.06896315]])

In [37]:
np.random.randint(1,100,10)

array([37, 37, 65, 75, 79, 24, 80, 83, 31,  9])

In [58]:
arr= np.arange(25)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
ranarr = np.random.randint(0,50,10)

In [61]:
ranarr

array([ 0,  5, 20, 24, 20,  2, 49, 39, 39,  3])

In [73]:
arr= arr.reshape(5,5)

In [74]:
ranarr

array([ 0,  5, 20, 24, 20,  2, 49, 39, 39,  3])

In [75]:
ranarr.max()

49

In [76]:
ranarr.min()

0

In [77]:
ranarr.argmax()

6

In [78]:
ranarr.argmin()

0

In [80]:
arr.shape # no parantheses

(5, 5)

In [81]:
arr.dtype

dtype('int64')

In [82]:
from numpy.random import randint 

# INDEXING AND SELECTION

In [85]:
arr = np.arange(0,11)

In [86]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[6]

6

In [89]:
arr[0:3]

array([0, 1, 2])

In [91]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [92]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [94]:
arr[0:5] = 100 

In [95]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [96]:
arr= np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
slice_of_arr = arr[0:6]

In [99]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [101]:
slice_of_arr [:] = 99

In [102]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [103]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [104]:
arr_copy = arr.copy()

In [106]:
arr_copy[:]=100

In [107]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [108]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [109]:
# need to make .copy or else we are just changing the original array 

# INDEXING 2D array/ Matrix


In [110]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [111]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [149]:
x=np.arange(0,100,5)

In [150]:
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [152]:
x_2d= x.reshape(5,4)

In [153]:
x_2d

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [157]:
x_2d[2:4,1:]

array([[45, 50, 55],
       [65, 70, 75]])

In [124]:
arr_2d[0][0]

5

In [125]:
arr_2d[0]

array([ 5, 10, 15])

In [129]:
arr_2d[2][1]

40

In [130]:
arr_2d[2,1]

40

In [132]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [139]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [158]:
#conditional selection

In [159]:
arr = np.arange(1,11)

In [160]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
bool_arr = arr > 5

In [164]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [165]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [166]:
#ONLY RETURNS INSTANCES WHERE IT IS TRUE 


In [167]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [168]:
arr[arr<3]

array([1, 2])

In [169]:
arr_2d = np.arange(50).reshape(5,10)

In [170]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [177]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## NUMPY OPERATIONS

In [178]:
arr = np.arange(0,11)

In [179]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
arr+arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [181]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [182]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [183]:
arr*4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [184]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [185]:
arr/4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ])

In [188]:
arr / arr

/Users/mk/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [189]:
#numpy issue warning vs error


In [190]:
1/arr

/Users/mk/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [192]:
arr**2 #power of 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [193]:
#universal array functions 

In [194]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [195]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [196]:
np.max(arr)

10

In [197]:
arr.max()

10

In [198]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [199]:
np.log(arr)

/Users/mk/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])